### ISSUE TITLE
Please revive the project

### ISSUE THREAD

**Issue by jantheodor** [pawelt/stacky#12]
Lovely app. Seems to have some issues when it comes to Win10. Only the last app in list shows it's icon.

**Comment by Chourando** [comment]
Win10 works like a charm, have no issues in years of using it🙄

**Comment by jantheodor** [comment]
> Win10 works like a charm, have no issues in years of using it🙄

[![Bild stackyscreenq3kyi.jpg auf abload.de](https://abload.de/thumb/stackyscreenq3kyi.jpg)](https://abload.de/image.php?img=stackyscreenq3kyi.jpg)

**Comment by AnnanFay** [comment]
@jantheodor I can confirm this issue. I implemented a hacky workaround for myself but never made a PR because I didn't manage to completely fix it.

If I remember correctly: The bug is failure to load icons initially, which causes the cache to be corrupt. My hack means icons are stored correctly in the cache correctly, but the loading issue is still there. So first load always has the strange icon issues, but all future loads work. Which makes it usable enough for me that I didn't put more time into investigating it.

I'm not actively developing the code, and very inexperienced with C++. But maybe someone can improve upon it.

Repo - https://github.com/AnnanFay/stacky
Commit - https://github.com/AnnanFay/stacky/commit/507bfc0a9f2811d20597f2d6d2431707592d4ce4

**Comment by pawelt** [comment]
Sorry for a rather later response. I am not maintaining the project anymore. Please feel free to fork it and change it in any way you want. Good luck! :)
